### ISSUE TITLE
Consider using redux-simple-router in example.

### ISSUE THREAD

**Issue by kurtharriger** [winstonewert/redux-reactions#3]
https://github.com/rackt/redux-simple-router

One thing I don't like about redux-router is that it adds non-serializable objects to the state. 
This makes it more difficult to serialize the react state such as with https://github.com/elgerlambert/redux-localstorage and it doesn't work with devtools (not looked into why but probably the non-serializable state)

Additionally, redux-router while not dead isn't being actively maintained. https://github.com/acdlite/redux-router/issues/172

**Comment by kurtharriger** [comment]
For reference this has already been converted on a PR.  
https://github.com/rackt/redux/pull/1152

There is however also an open issue regarding if the examples should use react-simple-router or stick with react-router, so maybe switching might be premature.
https://github.com/rackt/redux/issues/1145

**Comment by winstonewert** [comment]
Since I've just copied redux examples here, I'm inclined to wait until redux makes the switch.

**Comment by kurtharriger** [comment]
Sounds fair
