### ISSUE TITLE
Needs a LICENSE

### ISSUE THREAD

**Issue by kurtharriger** [winstonewert/redux-reactions#4]
Wouldn't be able to use this at work if it doesn't have a LICENSE.  
Would suggest MIT as it is same license as redux and very easy to get legal sign off in corporate environments

**Comment by winstonewert** [comment]
I thought I had put it under the MIT license as I put the LICENSE.md file in the repo? Or is that not sufficient?

**Comment by kurtharriger** [comment]
My bad. For some reason I thought it was missing. I'm guessing I was probably in the example folder at the time and assumed I was in project root.
